### ISSUE TITLE
Database install is a manual process

### ISSUE THREAD

**Issue by zgulde** [zgulde/cods#19]
Currently, no database is installed by default.

To install mysql 5.7, do the following after the initial server provisioning:

1. Login to the server

    ```
    myserver login
    ```

1. configure the mysql installation process

    ```
    # from the server
    sudo -s
    wget http://repo.mysql.com/mysql-apt-config_0.8.13-1_all.deb
    dpkg -i mysql-apt-config_0.8.13-1_all.deb
    ```

    1. From here, choose option 1, "MySQL Server & Cluster".
    1. Next choose version 5.7

1. Install mysql

    ```
    # still from the server
    apt update && apt install -y mysql-server
    ```

    Leave the root password blank for now

1. Setup your admin user

    1. Login to the mysql server

        ```
        # still logged in to the production server...
        mysql -uroot
        ```

    1. Create your admin mysql user

        ```
        CREATE USER you@localhost IDENTIFIED BY 'password';
        GRANT ALL on *.* TO you@localhost WITH GRANT OPTION;
        ```

        Replacing `you` with your server username, and `password` with your
        admin db password (found with `myserver credentials`).

**Comment by fmendozaro** [comment]
All these instructions are in: https://github.com/zgulde/cods/blob/master/docs/initial-server-setup.md We can close this issued
